server:
  port: 7001


eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #集群指向其他eureka
      defaultZone: http://eureka7002.com:7002/eureka/
      #单机指向自己
      #defaultZone: http://eureka7001.com:7001/eureka/
  server:
    enable-self-preservation: true   #禁用自我保护机制
    #eviction-interval-timer-in-ms: 2000  #Eureka服务端在收到最后一次心跳后等待时间上限，默认90秒，超时将剔除服务






